// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJROy10OdCgynM6KPr0rG_dZ9zBpsn9Bc',
    appId: '1:1087936669343:web:40f56809a28acbf31924aa',
    messagingSenderId: '1087936669343',
    projectId: 'langi-app',
    authDomain: 'langi-app.firebaseapp.com',
    databaseURL: 'https://langi-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'langi-app.appspot.com',
    measurementId: 'G-KPJ6BHRBTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcSAET7bTNDGIOv3c8JOCHlYR1kmm2EME',
    appId: '1:1087936669343:android:c56ce821e90fbe251924aa',
    messagingSenderId: '1087936669343',
    projectId: 'langi-app',
    databaseURL: 'https://langi-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'langi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpbjv-P5UcuMXzGFjHGGKVwzPigj21F4',
    appId: '1:1087936669343:ios:ad13cfbacb60405c1924aa',
    messagingSenderId: '1087936669343',
    projectId: 'langi-app',
    databaseURL: 'https://langi-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'langi-app.appspot.com',
    androidClientId: '1087936669343-8b6p829gad3ie14gum92sfodek5bh9fg.apps.googleusercontent.com',
    iosClientId: '1087936669343-0s9vpj1v3q0l855j6rt5d8j6rhbbfqmk.apps.googleusercontent.com',
    iosBundleId: 'dev.kums.langi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbpbjv-P5UcuMXzGFjHGGKVwzPigj21F4',
    appId: '1:1087936669343:ios:7a2f85fb3d6e904a1924aa',
    messagingSenderId: '1087936669343',
    projectId: 'langi-app',
    databaseURL: 'https://langi-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'langi-app.appspot.com',
    androidClientId: '1087936669343-8b6p829gad3ie14gum92sfodek5bh9fg.apps.googleusercontent.com',
    iosClientId: '1087936669343-d492nlfi6q9o54vchr6s07st773qg07u.apps.googleusercontent.com',
    iosBundleId: 'dev.kums.langi.RunnerTests',
  );
}
